# Generated by Django 2.1.2 on 2018-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wca_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
