# Generated by Django 2.1.2 on 2018-12-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubingevent',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cubingevent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
