version: '3'

services:
    db:
        container_name: rbvn_mysql_database
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
            - "MYSQL_DATABASE=rubikvn"
        volumes:
            - /var/lib/mysql
    web:
        container_name: rbvn_django_project
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        links:
            - db
        stdin_open: true
        tty: true
        depends_on:
            - db
