# Generated by Django 2.0.7 on 2018-08-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vietnamese',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subid', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('countryid', models.CharField(db_column='countryId', max_length=50)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=320)),
            ],
            options={
                'db_table': 'Vietnamese',
            },
        ),
        migrations.CreateModel(
            name='Viresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionid', models.CharField(db_column='competitionId', max_length=32)),
                ('eventid', models.CharField(db_column='eventId', max_length=6)),
                ('roundtypeid', models.CharField(db_column='roundTypeId', max_length=1)),
                ('pos', models.SmallIntegerField()),
                ('best', models.IntegerField()),
                ('average', models.IntegerField()),
                ('personname', models.CharField(blank=True, db_column='personName', max_length=80, null=True)),
                ('personid', models.CharField(db_column='personId', max_length=10)),
                ('personcountryid', models.CharField(blank=True, db_column='personCountryId', max_length=50, null=True)),
                ('formatid', models.CharField(db_column='formatId', max_length=1)),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('regionalsinglerecord', models.CharField(blank=True, db_column='regionalSingleRecord', max_length=3, null=True)),
                ('regionalaveragerecord', models.CharField(blank=True, db_column='regionalAverageRecord', max_length=3, null=True)),
            ],
            options={
                'db_table': 'ViResults',
            },
        ),
    ]
