# Generated by Django 2.0.7 on 2018-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('competition_id', models.CharField(max_length=191)),
                ('championship_type', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'championships',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cityname', models.CharField(db_column='cityName', max_length=50)),
                ('countryid', models.CharField(db_column='countryId', max_length=50)),
                ('information', models.TextField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('endmonth', models.PositiveSmallIntegerField(db_column='endMonth')),
                ('endday', models.PositiveSmallIntegerField(db_column='endDay')),
                ('eventspecs', models.CharField(blank=True, db_column='eventSpecs', max_length=256, null=True)),
                ('wcadelegate', models.TextField(blank=True, db_column='wcaDelegate', null=True)),
                ('organiser', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(max_length=240)),
                ('venueaddress', models.CharField(blank=True, db_column='venueAddress', max_length=120, null=True)),
                ('venuedetails', models.CharField(blank=True, db_column='venueDetails', max_length=120, null=True)),
                ('external_website', models.CharField(blank=True, max_length=200, null=True)),
                ('cellname', models.CharField(db_column='cellName', max_length=45)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('recordname', models.CharField(db_column='recordName', max_length=3)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('zoom', models.IntegerField()),
            ],
            options={
                'db_table': 'Continents',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('continentid', models.CharField(db_column='continentId', max_length=50)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='EligibleCountryIso2SForChampionship',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('championship_type', models.CharField(max_length=191)),
                ('eligible_country_iso2', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'eligible_country_iso2s_for_championship',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=54)),
                ('rank', models.IntegerField()),
                ('format', models.CharField(max_length=10)),
                ('cellname', models.CharField(db_column='cellName', max_length=45)),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sort_by', models.CharField(max_length=255)),
                ('sort_by_second', models.CharField(max_length=255)),
                ('expected_solve_count', models.IntegerField()),
                ('trim_fastest_n', models.IntegerField()),
                ('trim_slowest_n', models.IntegerField()),
            ],
            options={
                'db_table': 'Formats',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subid', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('countryid', models.CharField(db_column='countryId', max_length=50)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Rankaverage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personid', models.CharField(db_column='personId', max_length=10)),
                ('eventid', models.CharField(db_column='eventId', max_length=6)),
                ('best', models.IntegerField()),
                ('worldrank', models.IntegerField(db_column='worldRank')),
                ('continentrank', models.IntegerField(db_column='continentRank')),
                ('countryrank', models.IntegerField(db_column='countryRank')),
            ],
            options={
                'db_table': 'RanksAverage',
            },
        ),
        migrations.CreateModel(
            name='Ranksingle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personid', models.CharField(db_column='personId', max_length=10)),
                ('eventid', models.CharField(db_column='eventId', max_length=6)),
                ('best', models.IntegerField()),
                ('worldrank', models.IntegerField(db_column='worldRank')),
                ('continentrank', models.IntegerField(db_column='continentRank')),
                ('countryrank', models.IntegerField(db_column='countryRank')),
            ],
            options={
                'db_table': 'RanksSingle',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competitionid', models.CharField(db_column='competitionId', max_length=32)),
                ('eventid', models.CharField(db_column='eventId', max_length=6)),
                ('roundtypeid', models.CharField(db_column='roundTypeId', max_length=1)),
                ('pos', models.SmallIntegerField()),
                ('best', models.IntegerField()),
                ('average', models.IntegerField()),
                ('personname', models.CharField(blank=True, db_column='personName', max_length=80, null=True)),
                ('personid', models.CharField(db_column='personId', max_length=10)),
                ('personcountryid', models.CharField(blank=True, db_column='personCountryId', max_length=50, null=True)),
                ('formatid', models.CharField(db_column='formatId', max_length=1)),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
                ('regionalsinglerecord', models.CharField(blank=True, db_column='regionalSingleRecord', max_length=3, null=True)),
                ('regionalaveragerecord', models.CharField(blank=True, db_column='regionalAverageRecord', max_length=3, null=True)),
            ],
            options={
                'db_table': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sorry_message', models.CharField(max_length=172)),
            ],
            options={
                'db_table': 'Rounds',
            },
        ),
        migrations.CreateModel(
            name='Roundtype',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cellname', models.CharField(db_column='cellName', max_length=45)),
                ('final', models.IntegerField()),
            ],
            options={
                'db_table': 'RoundTypes',
            },
        ),
        migrations.CreateModel(
            name='Scramble',
            fields=[
                ('scrambleid', models.PositiveIntegerField(db_column='scrambleId', primary_key=True, serialize=False)),
                ('competitionid', models.CharField(db_column='competitionId', max_length=32)),
                ('eventid', models.CharField(db_column='eventId', max_length=6)),
                ('roundtypeid', models.CharField(db_column='roundTypeId', max_length=1)),
                ('groupid', models.CharField(db_column='groupId', max_length=3)),
                ('isextra', models.IntegerField(db_column='isExtra')),
                ('scramblenum', models.IntegerField(db_column='scrambleNum')),
                ('scramble', models.TextField()),
            ],
            options={
                'db_table': 'Scrambles',
            },
        ),
        migrations.DeleteModel(
            name='Vietnamese',
        ),
        migrations.DeleteModel(
            name='Viresults',
        ),
    ]
